### ISSUE TITLE
ADD CYBERSECURITY FOLDER

### ISSUE THREAD

**Issue by hack-parthsharma** [faizal108/Code-Cave#15]
@faizal108 Please add folder for cybersecurity enthusiasts

**Comment by hack-parthsharma** [comment]
And if possible please assign roles to the members for uploading content according to their interests

**Comment by faizal108** [comment]
Cyber Security is now available

**Comment by hack-parthsharma** [comment]
Great Thanks!

**Comment by faizal108** [comment]
@hack-parthsharma if possible then provide only the content
