### ISSUE TITLE
Remove PDFs and Add Content to README File

### ISSUE THREAD

**Issue by faizal108** [faizal108/Code-Cave#18]
Hey there! I noticed that some PDF files have been added to the placement folder in our shared repository on GitHub. While I appreciate the effort, I would prefer that we keep the content in a more organized and readable format.

Therefore, I kindly request that we remove the PDF files and instead add the content to a new section in the README.md file located in the placement folder. This will allow us to easily view and access the content without having to download and open multiple PDF files.

I believe that this approach will make it easier for all of us to collaborate and prepare for placements more effectively.

give the overview or required information for any topic.

<h1>Tasks</h1>
Remove all PDF files in the placement folder
Create a new section in the README.md file located in the placement folder
Add the content from the PDF files to the new section in the README.md file
Ensure the content is neat, clean, and concise, without any irrelevant information

**Comment by faizal108** [comment]
if you have notes you can upload in same folder.

**Comment by hack-parthsharma** [comment]
I'll try my best to do that
